io:
  reflectoring:
    aws:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
      eventbridge-scheduler:
        region: ${EVENTBRIDGE_SCHEDULER_REGION}
        target:
          arn: ${EVENTBRIDGE_SCHEDULER_TARGET_ARN}
          role-arn: ${EVENTBRIDGE_SCHEDULER_ROLE_ARN}
      sqs:
        region: ${AWS_SQS_REGION}
        queue-url: ${AWS_SQS_QUEUE_URL}
    user:
      account:
        deactivation-delay: ${USER_ACCOUNT_DEACTIVATION_DELAY}